name: PHP

on: workflow_call

jobs:
  php:
    name: PHP
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        php-version: [ '7.0', '8.0' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Paths filters
        uses: dorny/paths-filter@v2
        id: paths
        with:
          filters: |
            workflows: &workflows
              - '.github/actions/**/*.yml'
              - '.github/workflows/**/*.yml'
            composer: &composer
              - *workflows
              - 'composer.json'
              - 'composer.lock'
            php: &php
              - *workflows
              - *composer
              - '**/*.php'
            phpcs:
              - *workflows
              - *php
              - 'phpcs.xml'
            phpunit:
              - *workflows
              - *php
              - 'phpunit.xml'

      - name: Setup
        if: ${{ toJSON( steps.paths.outputs.changes ) != '"[]"' }}
        uses: ./.github/actions/setup-php
        with:
          cache_version: ${{ secrets.GH_ACTIONS_CACHE_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        if: ${{ toJSON( steps.paths.outputs.changes ) != '"[]"' && steps.cache-php-dependencies.outputs.cache-hit != 'true' }}
        run: composer install --no-progress --no-interaction --no-ansi

      - name: Make Composer packages available globally
        if: ${{ toJSON( steps.paths.outputs.changes ) != '"[]"' }}
        run: echo "${PWD}/vendor/bin" >> $GITHUB_PATH

      - name: Check syntax
        if: ${{ steps.paths.outputs.php == 'true' }}
        shell: bash {0}
        run: |
          LINT_JSON=$(parallel-lint --json --no-colors --no-progress --exclude .git --exclude .github --exclude vendor .)
          [[ "$LINT_JSON" =~ '"errors":[]' ]] && exit 0
          echo "$LINT_JSON" | jq -r '.results.errors[] | "::error file=\(.file),line=\(.line)::\(.message)"'
          exit 1

      - name: Lint code
        if: ${{ steps.paths.outputs.phpcs == 'true' }}
        uses: wearerequired/lint-action@v2
        with:
          continue_on_error: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
          php_codesniffer: true

      - name: Run tests
        if: ${{ steps.paths.outputs.phpunit == 'true' }}
        run: composer test
